services:
  - type: web
    name: Api_Museos
    env: php
    plan: free
    buildCommand: "composer install --optimize-autoloader --no-dev"
    startCommand: "/usr/local/bin/composer install && php-fpm"
    envVars:
      - key: PORT
        value: 10000
